spring:
  application:
    name: app-portal-web
  profiles:
    active: druid
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./file/

mybatis:
  configuration:
    map-underscore-to-camel-case: true


swagger:
  base-package:  com.zhwl.physical.controller
  title: 趣体检
  description: 趣体检
  version: 1.0
  terms-of-service-url: http://www.1234.com
  contact:
    name: yxs
    email: yangxshn@126.com

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /common/submitFeedback,/user/updateProfile,/user/updateBrief

